# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePreprocessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('fail', 'Fail')], help_text='status of the training', max_length=32, null=True)),
                ('additional_remarks', models.CharField(blank=True, help_text='Additional Information about the training. E.g. Information about failed trainings are logged here in case a training fails!', max_length=2048, null=True)),
                ('transform_categorical_to_binary', models.BooleanField(default=False, help_text='should the data be labeled binary as well?')),
                ('training_features_path', models.CharField(blank=True, max_length=256, null=True)),
                ('training_labels_path', models.CharField(blank=True, max_length=256, null=True)),
                ('evaluation_features_path', models.CharField(blank=True, max_length=256, null=True)),
                ('evaluation_labels_path', models.CharField(blank=True, max_length=256, null=True)),
                ('evaluation_labels_path_binary', models.CharField(blank=True, max_length=256, null=True)),
                ('training_labels_path_binary', models.CharField(blank=True, max_length=256, null=True)),
                ('binary_true_name', models.CharField(blank=True, default='perfect_condition', help_text='if binary transform categorical data to binary is true, all files in folder labeled with this name will be labeled as True while all other data will be labeled as false.', max_length=256, null=True)),
                ('input_folder_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('input_data_type', models.CharField(blank=True, choices=[('png', 'png'), ('wav', 'wav')], max_length=32, null=True)),
                ('preprocessing_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioPreprocessor',
            fields=[
                ('filepreprocessor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preprocessing.FilePreprocessor')),
                ('output_data_format', models.CharField(blank=True, choices=[('float', 'float'), ('int', 'int')], max_length=256, null=True)),
            ],
            bases=('preprocessing.filepreprocessor',),
        ),
        migrations.CreateModel(
            name='PicturePreprocessor',
            fields=[
                ('filepreprocessor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preprocessing.FilePreprocessor')),
                ('output_image_dimens', models.IntegerField(default=128)),
            ],
            bases=('preprocessing.filepreprocessor',),
        ),
    ]
