# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepreprocessor',
            name='machine_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
