# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0002_auto_20190122_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiopreprocessor',
            name='folder_name',
        ),
        migrations.RemoveField(
            model_name='filepreprocessor',
            name='input_file_format',
        ),
        migrations.RemoveField(
            model_name='filepreprocessor',
            name='output_file_format',
        ),
        migrations.AddField(
            model_name='filepreprocessor',
            name='input_folder_name',
            field=models.CharField(blank=True, default='/wav/', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='audiopreprocessor',
            name='binary_true_name',
            field=models.CharField(blank=True, default='perfect_condition', help_text='if binary transform categorical data to binary is true, all files in folder labeled with this name will be labeled as True while all other data will be labeled as false.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='audiopreprocessor',
            name='transform_categorical_to_binary',
            field=models.BooleanField(default=False, help_text='should the data be labeled binary as well?'),
        ),
    ]
