# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0005_picturepreprocessor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PicturePreprocessor',
        ),
        migrations.RemoveField(
            model_name='audiopreprocessor',
            name='transform_categorical_to_binary',
        ),
        migrations.RemoveField(
            model_name='filepreprocessor',
            name='input_folder_name',
        ),
        migrations.AddField(
            model_name='audiopreprocessor',
            name='input_folder_name',
            field=models.CharField(blank=True, default='/wav/', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='filepreprocessor',
            name='transform_categorical_to_binary',
            field=models.BooleanField(default=False, help_text='should the data be labeled binary as well?'),
        ),
        migrations.CreateModel(
            name='PicturePreprocessor',
            fields=[
                ('filepreprocessor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preprocessing.FilePreprocessor')),
                ('input_folder_name', models.CharField(blank=True, default='/png/', max_length=256, null=True)),
            ],
            bases=('preprocessing.filepreprocessor',),
        ),
        migrations.AlterField(
            model_name='Column',
            name='file_reformater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.FilePreprocessor'),
        ),
    ]
