# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0007_auto_20190123_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiopreprocessor',
            name='input_folder_name',
        ),
        migrations.RemoveField(
            model_name='picturepreprocessor',
            name='input_folder_name',
        ),
        migrations.AddField(
            model_name='audiopreprocessor',
            name='file_format',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='filepreprocessor',
            name='input_data_type',
            field=models.CharField(blank=True, choices=[('png', 'png'), ('wav', 'wav')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='filepreprocessor',
            name='input_folder_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='picturepreprocessor',
            name='bands',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='picturepreprocessor',
            name='frames',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
