# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0008_auto_20190123_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepreprocessor',
            name='preprocessing_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
