# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-08 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0009_filepreprocessor_preprocessing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='file_reformater',
        ),
        migrations.RemoveField(
            model_name='picturepreprocessor',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='picturepreprocessor',
            name='frames',
        ),
        migrations.AddField(
            model_name='picturepreprocessor',
            name='output_image_dimens',
            field=models.IntegerField(default=128),
        ),
        migrations.DeleteModel(
            name='Column',
        ),
    ]
