# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0010_auto_20190208_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiopreprocessor',
            name='file_format',
        ),
        migrations.AddField(
            model_name='audiopreprocessor',
            name='output_data_format',
            field=models.CharField(blank=True, choices=[('float', 'float'), ('int', 'int')], max_length=256, null=True),
        ),
    ]
