# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0002_auto_20190109_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmconfig',
            name='training_time',
            field=models.TimeField(blank=True, help_text='training time until completion or interrupt', null=True),
        ),
    ]
