# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0005_auto_20190109_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoKerasConfig',
            fields=[
                ('algorithmconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='training_server.AlgorithmConfig')),
                ('time_limit', models.IntegerField(blank=True, null=True)),
            ],
            bases=('training_server.algorithmconfig',),
        ),
    ]
