# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0006_autokerasconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmconfig',
            name='framework',
            field=models.CharField(choices=[('auto_keras', 'Auto-keras'), ('auto_sklearn', 'Auto-sklearn'), ('tpot', 'TPOT')], max_length=24),
        ),
    ]
