# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0010_auto_20190118_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReformater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('fail', 'Fail')], help_text='status of the training', max_length=32, null=True)),
                ('input_file_format', models.CharField(choices=[('parquet', 'parquet'), ('png', 'png'), ('wav', 'wav')], help_text='format of the input data', max_length=16)),
                ('output_file_format', models.CharField(choices=[('npy', 'npy'), ('csv', 'csv')], help_text='format of the output data', max_length=16)),
                ('input_feature_file_name', models.CharField(help_text='name of the input file originating from the file type root folder', max_length=256)),
                ('input_labels_file_name', models.CharField(help_text='name of the input labels originating from the file type root folder', max_length=256)),
                ('input_validation_feature_file_name', models.CharField(help_text='name of the input validation file originating from the file type root folder', max_length=256)),
                ('input_validation_labels_file_name', models.CharField(help_text='name of the input validation labels originating from the file type root folder', max_length=256)),
            ],
        ),
    ]
