# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0011_filereformater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereformater',
            name='output_file_format',
            field=models.CharField(choices=[('npy', 'npy'), ('csv', 'csv'), ('pkl', 'pkl')], help_text='format of the output data', max_length=16),
        ),
    ]
