# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0012_auto_20190118_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the column', max_length=256)),
                ('data_type', models.CharField(choices=[('category', 'category'), ('object', 'object'), ('int', 'int'), ('float', 'float'), ('bool', 'bool'), ('datetime64', 'datetime64'), ('timedelta[ns]', 'timedelta[ns]')], help_text='define the datatype this should be encoded as', max_length=128)),
                ('is_label', models.BooleanField(default=False, help_text='is this a label?')),
            ],
        ),
        migrations.AddField(
            model_name='filereformater',
            name='create_features_and_labels_from_features_file',
            field=models.BooleanField(default=False, help_text='Tick this checkbox for showing the advanced views to classify columns as features and labels to create two files, or execute advanced options like group_by or aggregations. As input input_feature_file and/or validation_feature_file will be taken'),
        ),
        migrations.AlterField(
            model_name='filereformater',
            name='input_feature_file_name',
            field=models.CharField(blank=True, help_text='name of the input file originating from the file type root folder', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='filereformater',
            name='input_labels_file_name',
            field=models.CharField(blank=True, help_text='name of the input labels originating from the file type root folder', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='filereformater',
            name='input_validation_feature_file_name',
            field=models.CharField(blank=True, help_text='name of the input validation file originating from the file type root folder', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='filereformater',
            name='input_validation_labels_file_name',
            field=models.CharField(blank=True, help_text='name of the input validation labels originating from the file type root folder', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='file_reformater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_server.FileReformater'),
        ),
    ]
