# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0013_auto_20190119_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filereformater',
            name='create_features_and_labels_from_features_file',
        ),
        migrations.RemoveField(
            model_name='filereformater',
            name='input_feature_file_name',
        ),
        migrations.RemoveField(
            model_name='filereformater',
            name='input_labels_file_name',
        ),
        migrations.RemoveField(
            model_name='filereformater',
            name='input_validation_feature_file_name',
        ),
        migrations.RemoveField(
            model_name='filereformater',
            name='input_validation_labels_file_name',
        ),
    ]
