# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0014_auto_20190119_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioReformater',
            fields=[
                ('filereformater_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='training_server.FileReformater')),
                ('folder_name', models.CharField(default='', max_length=256)),
                ('transform_categorical_to_binary', models.BooleanField(default=False)),
                ('binary_true_name', models.CharField(blank=True, default='no_fat_behavior', max_length=256, null=True)),
            ],
            bases=('training_server.filereformater',),
        ),
    ]
