# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0015_audioreformater'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereformater',
            name='additional_remarks',
            field=models.CharField(blank=True, help_text='Additional Information about the training. E.g. Information about failed trainings are logged here in case a training fails!', max_length=2048, null=True),
        ),
    ]
