# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0018_auto_20190119_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmconfig',
            name='handle_one_hot_encoding',
        ),
        migrations.AddField(
            model_name='algorithmconfig',
            name='input_one_hot_encoded',
            field=models.BooleanField(default=False, help_text='Handle one hot encoding by labeling the data with string instead to be accepted.'),
        ),
    ]
