# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0019_auto_20190119_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioreformater',
            name='filereformater_ptr',
        ),
        migrations.RemoveField(
            model_name='column',
            name='file_reformater',
        ),
        migrations.DeleteModel(
            name='AudioReformater',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='FileReformater',
        ),
    ]
