# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0021_algorithmconfig_freeze_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationresult',
            name='model',
        ),
        migrations.DeleteModel(
            name='ValidationResult',
        ),
    ]
