# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0025_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
