# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-25 15:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_server', '0026_auto_20190124_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='model_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=None, null=True, size=50),
        ),
    ]
