# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLog',
        ),
    ]
