# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_delete_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automltraining',
            name='additional_remarks',
            field=models.CharField(blank=True, help_text='Additional Information about the training. E.g. Information about failed trainings are logged here in case a training fails!', max_length=100000, null=True),
        ),
    ]
