# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-07 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_automltraining_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='automltraining',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='ml_models/'),
        ),
    ]
